name: keepalive

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:   # 👈 加这一行
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: curl sites
        run: |             
          curl -fsS https://www.totoo.fr/plateaux-2 || true
          curl -fsS https://pontcolbert.aimthai.fr/nos-specialite || true
          curl -fsS https://www.akira93.fr/sushi-2 || true
          curl -fsS https://colombes.dancesushi.fr/menus || true
          curl -fsS https://puteaux.dancesushi.fr/ || true
          curl -fsS https://www.sushibry.fr//special-roll-2 || true
          curl -fsS https://www.sushi-yummy.fr/ || true
          curl -fsS https://www.bonheur-ruan.fr/hors-d-oeuvre || true
          curl -fsS https://www.kunchapai.eu/plats-2 || true
          curl -fsS https://www.sweetcakeparis.fr/ || true
          curl -fsS https://osaka-docker-dkbbgygna0c2ezg8.westeurope-01.azurewebsites.net/makis-signatures || true





