name: send-emails-task

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  sendemails:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Send Emails Task
        run: |
          curl -X POST https://osaka-docker-dkbbgygna0c2ezg8.westeurope-01.azurewebsites.net/scheduletask/runtask \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "taskType=Nop.Services.Messages.QueuedMessagesSendTask, Nop.Services" || true
