name: osaka-nop-scheduler

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  scheduler:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger nop scheduler
        run: |
          curl -X POST https://osaka-docker-dkbbgygna0c2ezg8.westeurope-01.azurewebsites.net/scheduletask/runtask || true
